PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,avatar TEXT DEFAULT '',bio TEXT DEFAULT '',online INTEGER DEFAULT 0,role TEXT DEFAULT 'user',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS posts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,text TEXT DEFAULT '',media_url TEXT DEFAULT '',media_type TEXT DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS likes(id TEXT PRIMARY KEY,post_id TEXT NOT NULL,user_id TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(post_id,user_id));
CREATE TABLE IF NOT EXISTS comments(id TEXT PRIMARY KEY,post_id TEXT NOT NULL,user_id TEXT NOT NULL,text TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS friendships(id TEXT PRIMARY KEY,sender_id TEXT NOT NULL,receiver_id TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(sender_id,receiver_id));
CREATE TABLE IF NOT EXISTS follows(id TEXT PRIMARY KEY,follower_id TEXT NOT NULL,following_id TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(follower_id,following_id));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,sender_id TEXT NOT NULL,receiver_id TEXT NOT NULL,text TEXT NOT NULL,created_at TEXT NOT NULL,read_at TEXT DEFAULT NULL);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,type TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL,read_at TEXT DEFAULT NULL);
CREATE TABLE IF NOT EXISTS stories(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,media_url TEXT NOT NULL,media_type TEXT DEFAULT 'image',expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reels(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,video_url TEXT NOT NULL,caption TEXT DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,seller_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT DEFAULT '',price REAL DEFAULT 0,image_url TEXT DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS academy(id TEXT PRIMARY KEY,author_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT DEFAULT '',url TEXT DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS services(id TEXT PRIMARY KEY,provider_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT DEFAULT '',price REAL DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,service_id TEXT NOT NULL,buyer_id TEXT NOT NULL,provider_id TEXT NOT NULL,status TEXT DEFAULT 'pending',note TEXT DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,reporter_id TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL,status TEXT DEFAULT 'open',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS blocks(id TEXT PRIMARY KEY,blocker_id TEXT NOT NULL,blocked_id TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(blocker_id,blocked_id));
CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(created_at DESC); CREATE INDEX IF NOT EXISTS idx_messages_pair ON messages(sender_id,receiver_id,created_at); CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,created_at DESC);
